### ISSUE TITLE
Incorrect file or file format

### ISSUE THREAD

**Issue by mohitbhansali** [wx-chevalier/Awesome-Books-Notes#2]
Incorrect file or file format: https://github.com/wx-chevalier/Awesome-CS-Books/blob/master/Infrastructure/DistributedSystem/2017-Martin%20Kleppmann-Designing%20Data-Intensive%20Applications%20The%20Big%20Ideas%20Behind%20Reliable,%20Scalable,%20and%20Maintainable%20Systems.pdf

**Comment by mitchellirvin** [comment]
Bump. Trying to open this file on Mac:
> The file “2017-Martin Kleppmann-Designing Data-Intensive Applications The Big Ideas Behind Reliable, Scalable, and Maintainable Systems.pdf” could not be opened. It may be damaged or use a file format that Preview doesn’t recognize.

**Comment by kiquenet** [comment]
https://github.com/wx-chevalier/Awesome-CS-Books/blob/master/Infrastructure/2017-Kleppmann-Designing%20Data%20Intensive%20Applications.pdf cannot download in Windows 7 and Chrome
